version = 1
profile = "default"
engine = "8d284bb7b7f6fffad7d664aeda6932b974977f69870b88d3adfe5e6ee18285f0"

[[contracts]]
id = "src/AssetVault.sol:AssetVault"
descriptor = "clear-signing/descriptors/calldata-AssetVault-c3c36c1b.json"
exclusions = { }

[[contracts]]
id = "src/ClearToken.sol:ClearToken"
descriptor = "clear-signing/descriptors/calldata-ClearToken-2e2a2d3f.json"
exclusions = { }

[[contracts]]
id = "src/SwapRouter.sol:SwapRouter"
descriptor = "clear-signing/descriptors/calldata-SwapRouter-34f9445f.json"
exclusions = { }
